import type {
  AgentRun,
  AuditEvent,
  DocumentRecord,
  Evidence,
  Matter,
  SessionUser,
  WorkflowStep,
} from "./types";

export const demoUsers: Record<string, SessionUser> = {
  analyst: {
    id: "00000000-0000-4000-8000-000000000101",
    tenantId: "tenant_hanul",
    tenantName: "한울 세무법인",
    name: "곽현",
    email: "hyun.kwak@hanultax.demo",
    role: "ANALYST",
    initials: "곽",
  },
  reviewer: {
    id: "00000000-0000-4000-8000-000000000102",
    tenantId: "tenant_hanul",
    tenantName: "한울 세무법인",
    name: "이서윤",
    email: "seoyun.lee@hanultax.demo",
    role: "REVIEWER",
    initials: "이",
  },
  admin: {
    id: "00000000-0000-4000-8000-000000000103",
    tenantId: "tenant_hanul",
    tenantName: "한울 세무법인",
    name: "박민준",
    email: "minjun.park@hanultax.demo",
    role: "ADMIN",
    initials: "박",
  },
};

export const matters: Matter[] = [
  {
    id: "vat-2025-q4",
    client: "한빛테크 주식회사",
    taxType: "부가가치세",
    period: "2025년 제2기 확정신고",
    owner: "곽현",
    reviewer: "이서윤",
    status: "IN_REVIEW",
    risk: "HIGH",
    progress: 72,
    dueDate: "2026. 01. 26",
    openFindings: 4,
    evidenceCoverage: 96,
    updatedAt: "12분 전",
    summary: "매입세액 불공제 및 영세율 증빙 검토",
  },
  {
    id: "cit-2025",
    client: "리브온 커머스",
    taxType: "법인세",
    period: "2025 사업연도",
    owner: "김지민",
    reviewer: "이서윤",
    status: "NEEDS_INFO",
    risk: "MEDIUM",
    progress: 48,
    dueDate: "2026. 03. 31",
    openFindings: 7,
    evidenceCoverage: 81,
    updatedAt: "1시간 전",
    summary: "기업업무추진비 한도 및 연구개발비 세액공제 검토",
  },
  {
    id: "payroll-2026-01",
    client: "오름바이오",
    taxType: "원천세",
    period: "2026년 1월",
    owner: "최유진",
    reviewer: "박민준",
    status: "READY",
    risk: "LOW",
    progress: 92,
    dueDate: "2026. 02. 10",
    openFindings: 1,
    evidenceCoverage: 99,
    updatedAt: "어제",
    summary: "임직원 급여와 기타소득 원천징수 정합성 검토",
  },
  {
    id: "vat-2025-q3",
    client: "세림물산",
    taxType: "부가가치세",
    period: "2025년 제2기 예정신고",
    owner: "곽현",
    reviewer: "박민준",
    status: "CLOSED",
    risk: "LOW",
    progress: 100,
    dueDate: "2025. 10. 27",
    openFindings: 0,
    evidenceCoverage: 100,
    updatedAt: "2025. 10. 24",
    summary: "전자세금계산서 및 예정신고 검토",
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "doc_purchase_ledger",
    matterId: "vat-2025-q4",
    name: "2025_2기_매입매출장.xlsx",
    kind: "원장",
    size: "4.8 MB",
    status: "INDEXED",
    evidenceStatus: "APPROVED",
    pages: 0,
    chunks: 1248,
    piiClass: "RESTRICTED",
    uploadedBy: "곽현",
    updatedAt: "오늘 09:42",
    checksum: "sha256:1ca9…72e4",
    sourceType: "BUSINESS_RECORD",
  },
  {
    id: "doc_vat_return",
    matterId: "vat-2025-q4",
    name: "부가가치세_신고서_초안.pdf",
    kind: "신고서",
    size: "1.2 MB",
    status: "INDEXED",
    evidenceStatus: "APPROVED",
    pages: 18,
    chunks: 94,
    piiClass: "RESTRICTED",
    uploadedBy: "곽현",
    updatedAt: "오늘 10:13",
    checksum: "sha256:8bf2…c010",
    sourceType: "BUSINESS_RECORD",
  },
  {
    id: "doc_tax_act",
    matterId: "vat-2025-q4",
    name: "부가가치세법_업무안내_2025.pdf",
    kind: "세법령 자료",
    size: "8.1 MB",
    status: "INDEXED",
    evidenceStatus: "APPROVED",
    pages: 214,
    chunks: 863,
    piiClass: "INTERNAL",
    uploadedBy: "TaxOps 지식관리",
    updatedAt: "2026. 01. 03",
    checksum: "sha256:2aa4…a831",
    sourceType: "TAX_AUTHORITY",
  },
  {
    id: "doc_zero_rate",
    matterId: "vat-2025-q4",
    name: "수출실적명세서_보완본.csv",
    kind: "증빙",
    size: "840 KB",
    status: "PARSING",
    evidenceStatus: "PENDING",
    pages: 0,
    chunks: 0,
    piiClass: "CONFIDENTIAL",
    uploadedBy: "곽현",
    updatedAt: "2분 전",
    checksum: "sha256:b71d…418e",
    sourceType: "BUSINESS_RECORD",
  },
  {
    id: "doc_evidence_review",
    matterId: "vat-2025-q4",
    name: "기업업무추진비_업무관련성_소명서.txt",
    kind: "증빙",
    size: "12 KB",
    status: "INDEXED",
    evidenceStatus: "PENDING",
    pages: 1,
    chunks: 2,
    piiClass: "CONFIDENTIAL",
    uploadedBy: "곽현",
    updatedAt: "5분 전",
    checksum: "sha256:4d8c93f1…720e",
    sourceType: "BUSINESS_RECORD",
  },
];

export const evidence: Evidence[] = [
  {
    id: "ev_vat_001",
    tenantId: "tenant_hanul",
    matterId: "vat-2025-q4",
    documentId: "doc_tax_act",
    documentName: "부가가치세법 업무안내 2025",
    page: 87,
    section: "4.3 매입세액 불공제",
    excerpt:
      "사업과 직접 관련이 없는 지출의 매입세액과 기업업무추진비 관련 매입세액은 공제하지 않습니다.",
    contentHash: "d6ee4f739a0c",
    sourceType: "TAX_AUTHORITY",
    jurisdiction: "KR",
    effectiveFrom: "2025-01-01T00:00:00+09:00",
    effectiveTo: null,
    sourcePublisher: "국가법령정보센터",
    sourceUri: "https://law.go.kr/",
    acquiredAt: "2026-01-03T00:00:00+09:00",
    effectiveDate: "2025-01-01",
    score: 0.96,
  },
  {
    id: "ev_ledger_019",
    tenantId: "tenant_hanul",
    matterId: "vat-2025-q4",
    documentId: "doc_purchase_ledger",
    documentName: "2025년 제2기 매입매출장",
    page: null,
    section: "행 384–391 · 계정 812 기업업무추진비",
    excerpt:
      "공급가액 18,420,000원, 부가가치세액 1,842,000원입니다. 거래처 6곳 중 2곳은 업무 관련성 메모가 비어 있습니다.",
    contentHash: "47e291b0b5f1",
    sourceType: "BUSINESS_RECORD",
    jurisdiction: "KR",
    effectiveFrom: null,
    effectiveTo: null,
    sourcePublisher: null,
    sourceUri: null,
    acquiredAt: null,
    effectiveDate: "2025-12-31",
    score: 0.94,
  },
  {
    id: "ev_return_007",
    tenantId: "tenant_hanul",
    matterId: "vat-2025-q4",
    documentId: "doc_vat_return",
    documentName: "부가가치세 신고서 초안",
    page: 7,
    section: "매입세액 명세",
    excerpt:
      "불공제 매입세액 합계 1,102,000원이 반영되어 있으며 원장 분석 결과와 740,000원 차이가 있습니다.",
    contentHash: "93fbf7db413f",
    sourceType: "BUSINESS_RECORD",
    jurisdiction: "KR",
    effectiveFrom: null,
    effectiveTo: null,
    sourcePublisher: null,
    sourceUri: null,
    acquiredAt: null,
    effectiveDate: "2026-01-15",
    score: 0.91,
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "run_01JZX7A8VQ",
    matterId: "vat-2025-q4",
    status: "NEEDS_REVIEW",
    question: "매입세액 불공제 의심 항목과 신고서 반영 차이를 찾아 주세요",
    startedAt: "오늘 10:21",
    latencyMs: 8_420,
    tokens: 5_842,
    estimatedCostKrw: 42,
    retrievalHits: 8,
    evidenceCoverage: 96,
    promptVersion: "tax-memo.v1.3.0",
    model: "openai/gpt-5.6-sol",
    traceId: "tr_7a81f4c2",
  },
  {
    id: "run_01JZX74MDF",
    matterId: "vat-2025-q4",
    status: "COMPLETED",
    question: "영세율 첨부서류 누락 여부를 점검해 주세요",
    startedAt: "오늘 09:54",
    latencyMs: 6_180,
    tokens: 4_102,
    estimatedCostKrw: 29,
    retrievalHits: 6,
    evidenceCoverage: 100,
    promptVersion: "tax-memo.v1.3.0",
    model: "openai/gpt-5.6-sol",
    traceId: "tr_f4293d1b",
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    key: "INTAKE",
    label: "요청 분류",
    description: "민감정보 정책과 세목 범위 확인",
    status: "COMPLETE",
    latencyMs: 116,
  },
  {
    key: "RETRIEVE",
    label: "근거 검색",
    description: "업무 자료 5건과 세무 지식 3건 검색",
    status: "COMPLETE",
    latencyMs: 482,
  },
  {
    key: "DRAFT",
    label: "분석 초안",
    description: "결정론적 세액 계산 도구 1회 호출",
    status: "COMPLETE",
    latencyMs: 5_921,
  },
  {
    key: "VERIFY",
    label: "독립 검증",
    description: "분석 항목 6개 모두 근거 일치 확인",
    status: "COMPLETE",
    latencyMs: 1_901,
  },
  {
    key: "AWAITING_REVIEW",
    label: "전문가 검토",
    description: "검토자 승인 전 외부 반영 차단",
    status: "ACTIVE",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "audit_48f7",
    occurredAt: "10:29:18",
    actor: "근거 검증 에이전트",
    action: "AI_CITATION_VERIFIED",
    target: "run_01JZX7A8VQ",
    outcome: "SUCCESS",
    traceId: "tr_7a81f4c2",
    ipMasked: "system",
    prevHash: "9d6b…31a8",
    hash: "48f7…cb11",
  },
  {
    id: "audit_362c",
    occurredAt: "10:28:44",
    actor: "세무 분석 에이전트",
    action: "TOOL_CALCULATE_VAT",
    target: "vat-2025-q4",
    outcome: "SUCCESS",
    traceId: "tr_7a81f4c2",
    ipMasked: "system",
    prevHash: "1ab0…047f",
    hash: "9d6b…31a8",
  },
  {
    id: "audit_a112",
    occurredAt: "10:21:03",
    actor: "곽현",
    action: "AI_RUN_CREATED",
    target: "run_01JZX7A8VQ",
    outcome: "SUCCESS",
    traceId: "tr_7a81f4c2",
    ipMasked: "10.20.*.*",
    prevHash: "fd91…81b0",
    hash: "1ab0…047f",
  },
  {
    id: "audit_d993",
    occurredAt: "10:02:51",
    actor: "확인되지 않은 사용자",
    action: "CROSS_TENANT_READ_DENIED",
    target: "matter:cit-2025",
    outcome: "DENIED",
    traceId: "tr_13dace90",
    ipMasked: "172.18.*.*",
    prevHash: "8cc0…098d",
    hash: "fd91…81b0",
  },
];

export function getMatter(matterId: string) {
  return matters.find((matter) => matter.id === matterId);
}
